---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: doc
  sudo_command: '. /etc/profile;'

platforms:
  - name: centos-6.5
  - name: ubuntu-14.04
suites:
  - name: default
    run_list:
      - recipe[cutadapt::default]
    attributes:
