---
driver:
  name: docker

provisioner:
  name: chef_zero
  product_version: 14.10
  
verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[cutadapt::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
