name 'cutadapt'
maintainer 'The Authors'
maintainer_email 'chef@eaglegenomics.com'
license 'all_rights'
description 'Installs/Configures cutadapt'
long_description 'Installs/Configures cutadapt'
version '0.1.0'

depends 'build-essential'
depends 'magic_shell'
depends 'python'
